package:
  name: vcf2maf
  version: 1.7.0.elsablab

source:
  sha256: f84d1ecd1a048bdec7bb6b232d6bde8642f9626d2c6e5932429b9957bbb58e69
  url: https://github.com/ElsaB-Lab/DNA_Seq_vcf2maf/archive/refs/tags/v1.7.0.elsablab.tar.gz

build:
  noarch: generic
  number: 0

requirements:
  build: []
  run:
    - htslib
    - perl
    - samtools

test:
  commands:
    - vcf2maf.pl --help

about:
  dev_url: https://github.com/ElsaB-Lab/DNA_Seq_vcf2maf
  home: https://github.com/ElsaB-Lab/DNA_Seq_vcf2maf
  license: Apache-2.0
  license_family: APACHE
  summary: Convert a VCF into a MAF where each variant is annotated to only one of
    all possible gene isoforms.

extra:
  recipe-maintainers:
    - ypradat
  copy_test_source_files: true
  final: true
  notes: 'This package installs only vcf2maf and does not integrate with the variant-effect-predictor
    (VEP). To do so, please follow the instructions at https://github.com/mskcc/vcf2maf/blob/master/README.md.'
